
import "./globals.css";

export const metadata = {
  title: {
    default:"Home",
    template:"%s | Xeyn",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        {children}
      </body>
    </html>
  );
}
